title: zoë downey
email: zoe.downey@gmail.com
author: Zoë Downey

permalink: /:title/

# TBD: setup Google Analytics
analytics: UA-xxxx

sass:
  sass_dir: /assets/css/_sass

include:
  - _pages

exclude:
  - Makefile
  - tmp
  - photos.rb

collections:
  photos:
    permalink: /:path/
    output: true
      

exclude:
  - README.md
  - LICENSE.md
  - Makefile
  - bin
  - tmp

plugins:
  - jekyll-seo-tag
