name: Refresh photos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Make init
      run: make init

    - name: Make clobber
      run: make clobber

    - name: Make photos
      run: make photos
      env:
        FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
        FLICKR_SHARED_SECRET: ${{ secrets.FLICKR_SHARED_SECRET }}

    - name: Commit photos
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add _photos/
        git commit -m "Refreshed photos"

    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        branch: ${{ github.head_ref }}
